global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15672'] # RabbitMQ management endpoint

  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['rabbit-consumer-service:8080'] # Spring Boot application endpoint
#        labels:
#          application: 'Consumer service application'
